language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

env:
  - COMPOSER_OPTS=""
  - COMPOSER_OPTS="--prefer-lowest"

matrix:
  allow_failures:
    - php: hhvm

before_install:
  - composer self-update
  - composer update

script: phpunit --coverage-text
